'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace wsCaronte
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="dtSMTPMessage", [Namespace]:="http://schemas.datacontract.org/2004/07/wsCaronte"),  _
     System.SerializableAttribute()>  _
    Partial Public Class dtSMTPMessage
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private areaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private bodyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private codigoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private desdeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private emailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private email2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private email3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private email_rhField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private footerField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private hastaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private headerField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private id_usuarioField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private identificacionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private identificacion_tipoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private nombreField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private subjectField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ubicacionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private userField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property area() As String
            Get
                Return Me.areaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.areaField, value) <> true) Then
                    Me.areaField = value
                    Me.RaisePropertyChanged("area")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property body() As String
            Get
                Return Me.bodyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.bodyField, value) <> true) Then
                    Me.bodyField = value
                    Me.RaisePropertyChanged("body")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.codigoField, value) <> true) Then
                    Me.codigoField = value
                    Me.RaisePropertyChanged("codigo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property desde() As String
            Get
                Return Me.desdeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.desdeField, value) <> true) Then
                    Me.desdeField = value
                    Me.RaisePropertyChanged("desde")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property email() As String
            Get
                Return Me.emailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.emailField, value) <> true) Then
                    Me.emailField = value
                    Me.RaisePropertyChanged("email")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property email2() As String
            Get
                Return Me.email2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.email2Field, value) <> true) Then
                    Me.email2Field = value
                    Me.RaisePropertyChanged("email2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property email3() As String
            Get
                Return Me.email3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.email3Field, value) <> true) Then
                    Me.email3Field = value
                    Me.RaisePropertyChanged("email3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property email_rh() As String
            Get
                Return Me.email_rhField
            End Get
            Set
                If (Object.ReferenceEquals(Me.email_rhField, value) <> true) Then
                    Me.email_rhField = value
                    Me.RaisePropertyChanged("email_rh")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property footer() As String
            Get
                Return Me.footerField
            End Get
            Set
                If (Object.ReferenceEquals(Me.footerField, value) <> true) Then
                    Me.footerField = value
                    Me.RaisePropertyChanged("footer")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property hasta() As String
            Get
                Return Me.hastaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.hastaField, value) <> true) Then
                    Me.hastaField = value
                    Me.RaisePropertyChanged("hasta")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property header() As String
            Get
                Return Me.headerField
            End Get
            Set
                If (Object.ReferenceEquals(Me.headerField, value) <> true) Then
                    Me.headerField = value
                    Me.RaisePropertyChanged("header")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property id_usuario() As Integer
            Get
                Return Me.id_usuarioField
            End Get
            Set
                If (Me.id_usuarioField.Equals(value) <> true) Then
                    Me.id_usuarioField = value
                    Me.RaisePropertyChanged("id_usuario")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property identificacion() As String
            Get
                Return Me.identificacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.identificacionField, value) <> true) Then
                    Me.identificacionField = value
                    Me.RaisePropertyChanged("identificacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property identificacion_tipo() As String
            Get
                Return Me.identificacion_tipoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.identificacion_tipoField, value) <> true) Then
                    Me.identificacion_tipoField = value
                    Me.RaisePropertyChanged("identificacion_tipo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nombreField, value) <> true) Then
                    Me.nombreField = value
                    Me.RaisePropertyChanged("nombre")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property subject() As String
            Get
                Return Me.subjectField
            End Get
            Set
                If (Object.ReferenceEquals(Me.subjectField, value) <> true) Then
                    Me.subjectField = value
                    Me.RaisePropertyChanged("subject")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ubicacion() As String
            Get
                Return Me.ubicacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ubicacionField, value) <> true) Then
                    Me.ubicacionField = value
                    Me.RaisePropertyChanged("ubicacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property user() As String
            Get
                Return Me.userField
            End Get
            Set
                If (Object.ReferenceEquals(Me.userField, value) <> true) Then
                    Me.userField = value
                    Me.RaisePropertyChanged("user")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="wsCaronte.IwsCaronte")>  _
    Public Interface IwsCaronte
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IwsCaronte/get_pacientes_data", ReplyAction:="http://tempuri.org/IwsCaronte/get_pacientes_dataResponse")>  _
        Function get_pacientes_data() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IwsCaronte/get_pacientes_data", ReplyAction:="http://tempuri.org/IwsCaronte/get_pacientes_dataResponse")>  _
        Function get_pacientes_dataAsync() As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IwsCaronte/get_eps_data", ReplyAction:="http://tempuri.org/IwsCaronte/get_eps_dataResponse")>  _
        Function get_eps_data(ByVal codEps As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IwsCaronte/get_eps_data", ReplyAction:="http://tempuri.org/IwsCaronte/get_eps_dataResponse")>  _
        Function get_eps_dataAsync(ByVal codEps As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IwsCaronte/set_paciente_enviado", ReplyAction:="http://tempuri.org/IwsCaronte/set_paciente_enviadoResponse")>  _
        Sub set_paciente_enviado(ByVal s_epside As String, ByVal s_epstid As String, ByVal s_usuario As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IwsCaronte/set_paciente_enviado", ReplyAction:="http://tempuri.org/IwsCaronte/set_paciente_enviadoResponse")>  _
        Function set_paciente_enviadoAsync(ByVal s_epside As String, ByVal s_epstid As String, ByVal s_usuario As String) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IwsCaronte/set_paciente_administradora", ReplyAction:="http://tempuri.org/IwsCaronte/set_paciente_administradoraResponse")>  _
        Sub set_paciente_administradora(ByVal s_epside As String, ByVal s_epstid As String, ByVal s_usuario As String, ByVal s_epseps As String, ByVal s_epsnep As String, ByVal s_epsmai As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IwsCaronte/set_paciente_administradora", ReplyAction:="http://tempuri.org/IwsCaronte/set_paciente_administradoraResponse")>  _
        Function set_paciente_administradoraAsync(ByVal s_epside As String, ByVal s_epstid As String, ByVal s_usuario As String, ByVal s_epseps As String, ByVal s_epsnep As String, ByVal s_epsmai As String) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IwsCaronte/mensaje_enviar", ReplyAction:="http://tempuri.org/IwsCaronte/mensaje_enviarResponse")>  _
        Function mensaje_enviar(ByVal mensaje_in As wsCaronte.dtSMTPMessage) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IwsCaronte/mensaje_enviar", ReplyAction:="http://tempuri.org/IwsCaronte/mensaje_enviarResponse")>  _
        Function mensaje_enviarAsync(ByVal mensaje_in As wsCaronte.dtSMTPMessage) As System.Threading.Tasks.Task(Of Boolean)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IwsCaronteChannel
        Inherits wsCaronte.IwsCaronte, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class IwsCaronteClient
        Inherits System.ServiceModel.ClientBase(Of wsCaronte.IwsCaronte)
        Implements wsCaronte.IwsCaronte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function get_pacientes_data() As String Implements wsCaronte.IwsCaronte.get_pacientes_data
            Return MyBase.Channel.get_pacientes_data
        End Function
        
        Public Function get_pacientes_dataAsync() As System.Threading.Tasks.Task(Of String) Implements wsCaronte.IwsCaronte.get_pacientes_dataAsync
            Return MyBase.Channel.get_pacientes_dataAsync
        End Function
        
        Public Function get_eps_data(ByVal codEps As String) As String Implements wsCaronte.IwsCaronte.get_eps_data
            Return MyBase.Channel.get_eps_data(codEps)
        End Function
        
        Public Function get_eps_dataAsync(ByVal codEps As String) As System.Threading.Tasks.Task(Of String) Implements wsCaronte.IwsCaronte.get_eps_dataAsync
            Return MyBase.Channel.get_eps_dataAsync(codEps)
        End Function
        
        Public Sub set_paciente_enviado(ByVal s_epside As String, ByVal s_epstid As String, ByVal s_usuario As String) Implements wsCaronte.IwsCaronte.set_paciente_enviado
            MyBase.Channel.set_paciente_enviado(s_epside, s_epstid, s_usuario)
        End Sub
        
        Public Function set_paciente_enviadoAsync(ByVal s_epside As String, ByVal s_epstid As String, ByVal s_usuario As String) As System.Threading.Tasks.Task Implements wsCaronte.IwsCaronte.set_paciente_enviadoAsync
            Return MyBase.Channel.set_paciente_enviadoAsync(s_epside, s_epstid, s_usuario)
        End Function
        
        Public Sub set_paciente_administradora(ByVal s_epside As String, ByVal s_epstid As String, ByVal s_usuario As String, ByVal s_epseps As String, ByVal s_epsnep As String, ByVal s_epsmai As String) Implements wsCaronte.IwsCaronte.set_paciente_administradora
            MyBase.Channel.set_paciente_administradora(s_epside, s_epstid, s_usuario, s_epseps, s_epsnep, s_epsmai)
        End Sub
        
        Public Function set_paciente_administradoraAsync(ByVal s_epside As String, ByVal s_epstid As String, ByVal s_usuario As String, ByVal s_epseps As String, ByVal s_epsnep As String, ByVal s_epsmai As String) As System.Threading.Tasks.Task Implements wsCaronte.IwsCaronte.set_paciente_administradoraAsync
            Return MyBase.Channel.set_paciente_administradoraAsync(s_epside, s_epstid, s_usuario, s_epseps, s_epsnep, s_epsmai)
        End Function
        
        Public Function mensaje_enviar(ByVal mensaje_in As wsCaronte.dtSMTPMessage) As Boolean Implements wsCaronte.IwsCaronte.mensaje_enviar
            Return MyBase.Channel.mensaje_enviar(mensaje_in)
        End Function
        
        Public Function mensaje_enviarAsync(ByVal mensaje_in As wsCaronte.dtSMTPMessage) As System.Threading.Tasks.Task(Of Boolean) Implements wsCaronte.IwsCaronte.mensaje_enviarAsync
            Return MyBase.Channel.mensaje_enviarAsync(mensaje_in)
        End Function
    End Class
End Namespace
